### ISSUE TITLE
f32 vs f64

### ISSUE THREAD

**Issue by walkr** [georust/rust-geo#100]
Hello, 

I've noticed that when computing haversine distance between points yields wildly different results when using f32 vs f64 for coordinate types.

```rust

extern crate geo;

use geo::Point;
use geo::algorithm::haversine_distance::HaversineDistance;

#[warn(dead_code)]
fn distance_32(){
    let p = Point::new(-77.036585f32, 38.897448f32);
    let dist = p.haversine_distance(&Point::new(-77.009080f32, 38.889825f32));
    println!("Distance = {:?}", dist)
}

#[warn(dead_code)]
fn distance_64(){
    let p = Point::new(-77.036585f64, 38.897448f64);
    let dist = p.haversine_distance(&Point::new(-77.009080f64, 38.889825f64));
    println!("Distance = {:?}", dist)
}


fn main() {

    distance_32();
    distance_64();
}

```

Output

```shell
Distance (f32) = 3114.3247
Distance (f64) = 2529.6506398715096
```
Is this normal?

Thanks!

**Comment by frewsxcv** [comment]
According to http://www.movable-type.co.uk/scripts/latlong.html, it should be round 2527km

<img width="755" alt="screen shot 2017-03-14 at 9 23 01 am" src="https://cloud.githubusercontent.com/assets/416575/23902524/da75748a-0897-11e7-9c47-476a697ca899.png">

So it looks like something might be wrong for f32? cc @urschrei

**Comment by urschrei** [comment]
Hmm @Turbo87 and @tmcw implemented this. I know Haversine can be unstable when calculating distances using near-antipodal points, but I don't think that's what's going on here…

**Comment by TeXitoi** [comment]
The formula doesn't look like Havesine. It's the spherical law of cosines that is known to be subject to imprecisions when the angle is small.  I think the function must be rewritten to really use the Havesine formula, else the name of the function is really missleading.

**Comment by urschrei** [comment]
I've ported the algorithm from movable_type to [my branch](https://github.com/urschrei/rust-geo/blob/haversine_fix/src/algorithm/haversine_distance.rs#L26-L41), and added the points that caused this issue as `test3`, but the results are still wrong, and now I'm even more confused. There must be a high-quality C / CPP implementation somewhere.

**Comment by TeXitoi** [comment]
@urschrei in https://github.com/urschrei/rust-geo/blob/haversine_fix/src/algorithm/haversine_distance.rs#L26-L41 it should be
```rust
let c = two * a.sqrt().asin();
```
no? Where your atan2 come from?

And better to use `.powi()` than `.powf()`

**Comment by urschrei** [comment]
@TeXitoi movable type used the more complicated `atan2` for some reason – I've switched to `asin` (and `powi`), but it works out to the same (wrong?) answer.

**Comment by TeXitoi** [comment]
What's the results for f32 and f64 with your version?

**Comment by urschrei** [comment]
Argh, I'd reversed lat and lon coords in my test. For the points above:
`f32`: 2526.8318
`f64`: 2526.820014113592

Which is correct. I've pushed the updated test. If we're happy with this, I'll update the other two tests and turn it into a PR.

**Comment by frewsxcv** [comment]
Fixed in https://github.com/georust/rust-geo/issues/100
