### ISSUE TITLE
Polygon centroid calculation should account for interior holes

### ISSUE THREAD

**Issue by urschrei** [georust/rust-geo#111]
It doesn't at the moment, meaning that rotation around a polygon centroid (see #107) is only possible for simple polygons. If anyone has suggestions for existing clean algorithm implementations, I'm happy to rewrite the existing implementation.

**Comment by TeXitoi** [comment]
That's just a ponderated sum of the centroid of the individual polygon weighted by their area (resp length for line strings) (negative area for holes).

**Comment by urschrei** [comment]
So I think I have this working, but I've run into a snag: in order for the calculation to work you have to treat the interior rings as polygons when calculating their centroids, as opposed to LineStrings.
I've managed the weighted sum (https://github.com/urschrei/rust-geo/blob/allow_centroid_holes/src/algorithm/centroid.rs#L83-L102), but I'm using a `clone()` call to construct the Polygon, which feels like a waste.
