### ISSUE TITLE
Rebrand?

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geo#12]
From #rust-geo on IRC:

```
6:11 PM <@dremonkey> also I have a good name for rust-geo if interested
6:11 PM <@dremonkey> in changing
6:12 PM <@dremonkey> noticed a lot of rust libs play off of elements or iron... so was thinking lodestone would be kinda fun
```

Not suggesting we need to, but when (if?) this library ever matures and we ever want to rebrand, ideas can be shared here.

Specifically with the 'lodestone' idea above, I think it's very creative, though we lose a bit of the implicit description of the library (unless there is some large overlap in software developers and geologists I'm not aware of)

**Comment by Turbo87** [comment]
I've just found this library by searching for "rust geo" on Google and IMHO changing the name to something like "lodestone" would certainly make it harder to find and remember.

**Comment by calvinmetcalf** [comment]
also when everyone is making very similar puns it makes telling libraries apart very hard

**Comment by tmcw** [comment]
Another -1, rust-geo is nice & direct.

**Comment by frewsxcv** [comment]
Not much support for rebranding, so closing this.
