### ISSUE TITLE
semver breakage

### ISSUE THREAD

**Issue by TeXitoi** [georust/rust-geo#130]
geo-0.4.7 depends on serde-1, which is a breaking change. geo should be 0.5.

**Comment by frewsxcv** [comment]
You're right, good catch. Should I yank versions >= 0.4.7 and publisb. 0.5?

**Comment by KodrAus** [comment]
We had a similar situation with `chrono` and `serde`. They yanked the patch that bumped `serde`'s major version.

**Comment by TeXitoi** [comment]
I think so, yes.

**Comment by rory** [comment]
To be technically correct (the best kind of correct), [semver](http://semver.org/) says that if you're 0.x.y then you're allowed do whatever you want. 😉

> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

And the bikeshed should be blue.

**Comment by frewsxcv** [comment]
Actually, before I make any versioning changes, how is this a breaking change? I understand that if I did a dependency upgrade, and that dependency was exposed through this crate, that could be a breaking change (e.g. upgrading serde 0.9 to 1.0 in a minor version release). But in this particular case, I'm just adding a dependency which no one relies on yet.

**Comment by KodrAus** [comment]
Oh this is adding `serde` as a dependency when it wasn't there before? That shouldn't be a breaking change. If it was I would think our coherence rules weren't doing their job.

**Comment by TeXitoi** [comment]
Mmm, looks like your right, no breaking changes. I was `cargo update`ing and had problem with compilation. I thought it was because of geo, but maybe not, I see in the commit that I also specified versions on other crates.

**Comment by TeXitoi** [comment]
I confirm that upgrading to 0.4.9 using cargo update didn't break my build, the breaking was caused by a "*" on the crate geojson.

**Comment by frewsxcv** [comment]
If people are interested, we can make the serde stuff opt-in for the next major change release (since it'd be a breaking change).
