### ISSUE TITLE
Extract cross product operation

### ISSUE THREAD

**Issue by mbattifarano** [georust/rust-geo#133]
The cross product of two points is implemented inline in several places. We should implement a cross product method directly on `Point`.

See also: https://github.com/georust/rust-geo/pull/132#discussion_r131529789

**Comment by frewsxcv** [comment]
here are the two implementations which could be put on `Point`:

* https://github.com/georust/rust-geo/blob/523ac0393744d5216ae525188678691abfb7c9a4/src/algorithm/extremes.rs#L70-L76
* https://github.com/georust/rust-geo/blob/523ac0393744d5216ae525188678691abfb7c9a4/src/algorithm/convexhull.rs#L38-L56

**Comment by Jay9596** [comment]
I would like to work on this issue.
Should I change the occurrences or leave them be and change them after submitting the PR with the cross fn as part of Point.

**Comment by frewsxcv** [comment]
@Jay9596 thanks for taking this on! you can go ahead and change the existing occurrences to use the new method
