### ISSUE TITLE
Coordinates are stored as Floats. Could they also be integers?

### ISSUE THREAD

**Issue by rory** [georust/rust-geo#137]
Currently, the fundamental "unit" is `num_traits::Float`, i.e. all x/ys (or lat/longs) are represented as `Float`. And I wonder if this needs to be? I have a project which does things and eventually projects/rasterises geometry to a integer grid, and there's no 100% easy way to store this. Yes I can use Floats, and then truncate at the very end, but that seems subpar. I'm not suggesting removing `Float`, but *expanding* what can be stored in/as a Geometry/etc.

Obviously some algorithms wouldn't work on integers (e.g. `Area` calculation), and the Area trait would still use `T: Float`. 

I have a branch locally which does this, and it's that much of a change to support `PrimInt` and `Float`.

What do yous think?

**Comment by mbattifarano** [comment]
Would you mind pushing the branch? I'm curious to take a look. I don't think I understand how this would work since many operations on integral geometries won't always return integral geometries.

For example, the intersection of two integral line segments: `l1 = (0, 0), (2, 1)` and `l2 = (0, 1), (1, 0)` is `(2/3, 1/3)`. Walking through the algorithm with ints (and integer division) you'd get `(0,0)` (or one of the other endpoints depending on the implementation). 

At first glance, I do think a rasterize operation onto a given grid at the end is the way to go -- that way the user could provide whatever grid they wanted.

**Comment by rory** [comment]
There's a branch here: https://github.com/rory/rust-geo/tree/any-num

[This commit](https://github.com/rory/rust-geo/commit/2229df72e982bd8cad227203249da56d67d06d37) is how I implemented it. I created `CoordinateType` to replace the `Float`. Then it's almost just a find and replace to use that instead.

Some operations (like line intersection or area) might not make sense, and still require the `Float` trait.

**Comment by rory** [comment]
I have worked on this a little more, and reworked it against current master. The new branch is https://github.com/rory/rust-geo/tree/any-num-coordinates

Any feedback? Is this something that `rust-geo` should have?

**Comment by jdroenner** [comment]
I like it. Operations can still limit the generic type to Float if they require it.

**Comment by frewsxcv** [comment]
yep, looks good to me too 👍

**Comment by urschrei** [comment]
I don't do much raster stuff atm so I'm not really qualified, but it definitely _seems_ like a good idea. We should definitely explain what's going on in the docs, point out caveats etc. when this turns into a PR, though.

**Comment by rory** [comment]
My motivation for this was when working with the MVT vector tile format for OpenStreetMap. In that file format, vector geometry is stored as integers.

---
> the intersection of two integral line segments

Yes I had those problems. For my use case I just choose some point that's "good enough". the `Intersection` algoritm is probably one where you `Floats` are required.

---

> I do think a rasterize operation onto a given grid at the end is the way to go -- that way the user could provide whatever grid they wanted.

You can do this with the [MapCoords](https://github.com/georust/rust-geo/blob/17ae39c433c9ecbb5ea8529ed82b561225a59c2b/src/algorithm/map_coords.rs#L6-L36) trait, which allows you to change the types. You could convert `f64` to `i32` etc. (That's one of the reasons  I wrote it like this.

---

> We should definitely explain what's going on in the docs, point out caveats etc. when this turns into a PR, though.

Agreed. I didn't do the "grunt work" in the fork because I wasn't sure if the idea was acceptable and likely to be merged. Now that I see the support, I'll work on cleaning it up and making a real PR.

**Comment by rory** [comment]
PR #187 fixes this, so I'll close the issue. Discussion should take place on the PR
