### ISSUE TITLE
Possible bug with polygon to polygon intersections.

### ISSUE THREAD

**Issue by umurgdk** [georust/rust-geo#140]
I needed to divide a region (polygon) to 50x50 meter cells, what I did was looping through the width and height of the region's bounding box and create a cell for every step then test it via `bigger_polygon.intersects(&cell_polygon)`. If I'm not doing stupid mistake it seems like a there is bug on calculating intersections. 

And here is the visualization, as we can see red square shouldn't return true for intersection test.
![geo](https://user-images.githubusercontent.com/624974/29236439-65da367c-7f45-11e7-950d-357a50665e44.png)

Here is the failing test case. POINTS array are black polygon in the visual and small_polygon is the red square.
```rust
#[cfg(test)]
mod test {
    use geo::Polygon;
    use geo::intersects::Intersects;

    #[test]
    fn interstects() {
        let big_polygon = Polygon::new(POINTS.to_vec().into(), vec![]);

        // Just a 50x50 meters rect
        let small_polygon = Polygon::new(vec![
            ( 127.0072984994905, 37.577366522199405 ),
            ( 127.0078658729216, 37.577366520841686 ),
            ( 127.0078658729216, 37.57691686003872 ),
            ( 127.0072984994905, 37.57691686139645 )
        ].into(), vec![]);

        // It shouldn't intersect with bigger polygon
        assert_eq!(big_polygon.intersects(&small_polygon), false);
    }

    pub const POINTS: [(f64, f64); 26] = [
        ( 126.99294090270998, 37.5772698028868 ),
        ( 126.99240982532503, 37.57736758665555 ),
        ( 126.99149787425996, 37.5764237553521 ),
        ( 126.99141204357149, 37.57567548419531 ),
        ( 126.99364364147186, 37.57203605817081 ),
        ( 126.99377775192261, 37.57054367201618 ),
        ( 126.99527978897093, 37.57054792387107 ),
        ( 126.99573040008544, 37.56655107315775 ),
        ( 127.00274169445039, 37.56686572662952 ),
        ( 127.00982272624971, 37.56547103626546 ),
        ( 127.01042890548705, 37.5659387707002 ),
        ( 127.01180756092073, 37.56629594774544 ),
        ( 127.01261758804321, 37.56694226375953 ),
        ( 127.01248347759248, 37.56781818309174 ),
        ( 127.009693980217,   37.568872674254486 ),
        ( 127.00952231884003, 37.570369345756944 ),
        ( 127.010595202446,   37.57149182964705 ),
        ( 127.00900733470918, 37.573056475933804 ),
        ( 127.00767695903781, 37.57298844851792 ),
        ( 127.00883567333221, 37.571253728417325 ),
        ( 126.99647605419162, 37.57070949417681 ),
        ( 126.99636876583098, 37.57202755463073 ),
        ( 126.99677646160124, 37.572771610715066 ),
        ( 126.99616760015486, 37.574859179812385 ),
        ( 126.99551582336427, 37.57638974318991 ),
        ( 126.99294090270998, 37.5772698028868 )
    ];
}
```

**Comment by urschrei** [comment]
Could you supply a reduced test case showing expected vs actual intersection behaviour? There's a lot going on in your example code, and a minimal case with some of the values you're using would really help.

**Comment by umurgdk** [comment]
@urschrei I've updated the issue with reduced test code, and the visual

**Comment by umurgdk** [comment]
As a workaround I could achieve my goal testing if polygon `contains` any of the points of the cell.

**Comment by urschrei** [comment]
Thanks for simplifying this, @umurgdk. It looks like the outer ring in `small_polygon` isn't closed. If I add a `(127.0072984994905, 37.577366522199405)` tuple to the end of the vec, the intersection test correctly returns `false` for me. You can also check this by checking whether the two `LineStrings` intersect, even if the small one isn't closed (they're correctly shown as non-intersecting for me).  

This isn't a bug, but it's a usability issue for us, since we don't automatically close rings when the `new` constructor is called with open `LineStrings`.

**Comment by umurgdk** [comment]
Oh thanks for the explanation that makes sense. I will make sure my polygons are closed :)
