### ISSUE TITLE
Update MapCoords to lazily return an iterator instead of always collecting

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geo#141]
See my comment here: https://github.com/georust/rust-geo/pull/136#issuecomment-322068858

**Comment by rory** [comment]
I'm not 100% sure I follow you? Do you mean (for example) that `.map_coords(...)` on a MultiPolygon should return a `Interator<Item=Polygon>`? And that the caller would have to `.collect()` them into a MultiPolygon?

If so, I can kinda see your point, and the name `map` does sound iterator-like. But are there situations which would want to do further Iterator-like things on the results (like filter)? I do like having a single function which does the coversion.

**Comment by frewsxcv** [comment]
Yeah, sorry about this. Ignore this GitHub issue, I was way too tired when I wrote this and after thinking about this again, there's not any way to make `MapCoords` lazy in any realistic way right now. Sorry for the noise
