### ISSUE TITLE
Intersection algorithm says a line intersects with a point not on it

### ISSUE THREAD

**Issue by eeeeeta** [georust/rust-geo#144]
I'm using the following code:

```rust
extern crate geo;
use geo::*;
use geo::algorithm::intersects::Intersects;
fn main() {
    let ln = Line::new(Point::new(51.3561738,0.1089333), Point::new(51.3555692,0.1097743));
    let pt = Point::new(51.3566007,0.1083048);
    assert!(ln.intersects(&pt));
}
```
which fails the assertion:
```
thread 'main' panicked at 'assertion failed: ln.intersects(&pt)', src/main.rs:7:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

As far as I can see, the point (51.3566007,0.1083048) is not on the line segment given (although it is on the *line*, i.e. what you get if you extend the line segment to infinity in both directions):

![spectacle ns2968](https://user-images.githubusercontent.com/9402870/29627198-32187406-8829-11e7-8d87-fb01cea72abd.png)

**Comment by eeeeeta** [comment]
As a workaround, `distance()` seemed to work (it returns `0.0007597735583716097`)...

**Comment by eeeeeta** [comment]
God damnit, I'm an idiot. Please ignore this issue... :(

(turned out I had written `assert(ln.intersects())` instead of `!ln.intersects` in this reduced test case, and I was using `||` instead of `&&` in my code that was broken....

**Comment by urschrei** [comment]
np! I was about to ask whether the test was correct when you beat me to it. Looks like you're building something OSM and rail-related…ping us if / when it's something public?

**Comment by eeeeeta** [comment]
@urschrei Yup, your guesses are correct...I'm trying to work out when level crossings close & open in the UK, using OSM and Network Rail data. Not as easy as I'd hoped! I'll ping you if I ever manage to make anything useful.
