### ISSUE TITLE
Prelude

### ISSUE THREAD

**Issue by Michael-F-Bryan** [georust/rust-geo#146]
A common Rust pattern is to expose some top-level `prelude` module which re-exports all the commonly-used traits in a module. 

Seeing as a lot of the functionality for various operations is separated into their various submodules in `geo::algorithms`, and you have to manually import each trait, would it be possible to expose a `geo::prelude` module which people can glob import (e.g. `use geo::prelude::*`)?

**Comment by frewsxcv** [comment]
Yeah, I agree. Considering all the traits we have, it seems reasonable to offer a `prelude`. I'm thinking, for now, it should just have the traits (e.g. `MapCoords`, `Translate`, etc) and not the types (e.g. `Polygon`, `Point`, etc). Does that sound reasonable?

**Comment by Michael-F-Bryan** [comment]
I agree, don't really want to export types in the `prelude` because it's mainly for automatically bringing traits into scope so you can use their methods. Besides, users can already do `use geo::Polygon`.
