### ISSUE TITLE
Seemingly unnecessary bounds on `Translate`

### ISSUE THREAD

**Issue by Michael-F-Bryan** [georust/rust-geo#147]
Is the `FromPrimitive` bound still necessary for the `Translate` trait's blanket impl? It doesn't look like `MapCoords` requires `FromPrimitive`, and I can't see anything which explicitly requires it.

The code in question:

```rust
impl<T, G> Translate<T> for G
    where T: Float + FromPrimitive,
        G: MapCoords<T, T, Output=G>
{
    fn translate(&self, xoff: T, yoff: T) -> Self {
        self.map_coords(&|&(x, y)| (x + xoff, y + yoff))
    }
}
```

This isn't really an issue in practice because all types implementing `num_traits::Float` are also `FromPrimitive`, but it feels a bit odd to add the extra constraint.

---

Also, I don't think the `&` in front of the closure is necessary. `MapCoords::map_coords()` should be generic over anything which is `Fn(&(T, T)) -> (NT, NT)` so you can skip the extra syntax and dynamic dispatch, although fixing that now would be a breaking change...

**Comment by frewsxcv** [comment]
>  It doesn't look like MapCoords requires FromPrimitive, and I can't see anything which explicitly requires it.

Agreed, I think we can get rid of it :+1:

> Also, I don't think the & in front of the closure is necessary. MapCoords::map_coords() should be generic over anything which is Fn(&(T, T)) -> (NT, NT) so you can skip the extra syntax and dynamic dispatch, although fixing that now would be a breaking change...

This might be a selfish position to hold, but I'm okay making breaking changes somewhat frequently for rust-geo. I feel it's still early on in the crates lifetime and not many projects depend on it yet. Also, this sort of breaking change is not one that would cause a lot of issues for users I imagine

**Comment by Michael-F-Bryan** [comment]
> Also, this sort of breaking change is not one that would cause a lot of issues for users I imagine

I just tried this out in [the playground] and apparently a pointer to a `Fn` closure also implements `Fn`. So that means we can change it and all the old code will still compile.

Should I make a PR for this?

[the playground]: https://play.rust-lang.org/?gist=483a6f9d1eac58f6399b10a6afc723c8&version=stable

**Comment by frewsxcv** [comment]
Yep, sounds good to me!
