### ISSUE TITLE
Getting bearing between two points?

### ISSUE THREAD

**Issue by pavelmachek** [georust/rust-geo#185]
I can use haversine_destination to convert point, bearing and distance to second point. Is there reverse operation available? I can use haversine_distance() to get distance of two points, but I can't get bearing...

**Comment by urschrei** [comment]
Hmm I don't do much with Haversine, @mkulke, got any ideas?

**Comment by pavelmachek** [comment]
For now I worked around the problem with:

```
fn get_bearing(origin : & geo::Point<f64>, destination : & geo::Point<f64>) -> f64 {
// https://gist.github.com/geografa/1366401
        let (lon1, lat1) = ( origin.x().to_radians(), origin.y().to_radians() );
        let (lon2, lat2) = ( destination.x().to_radians(), destination.y().to_radians() );
        let dlon = lon2-lon1;

        let bearing = f64::atan2(f64::sin(dlon)*f64::cos(lat2),f64::cos(lat1)*f64::sin(lat2)-f64::sin(lat1)*f64::cos(lat2)*f64::cos(dlon));

        bearing.to_degrees()
}
```

**Comment by mkulke** [comment]
@pavelmachek 

actually i think your implementation is canonical. maybe worth adding?

```
S = cos φB sin ∆L
C = cos φA sin φB − sin φA cos φB cos ∆L
beta = atan2(S, C);
```
source: https://dtcenter.org/met/users/docs/write_ups/gc_simple.pdf

**Comment by pavelmachek** [comment]
Yes, the code should be ok. But I guess I do not know enough about rust templates and cargo to generate proper patch. I'd like rust-geo to gain that functionality.

**Comment by mkulke** [comment]
alrighty, i quickly added the trait in #186. it's useful for me as well.

**Comment by urschrei** [comment]
Ha amazing I wrote one just before I left work and didn’t push it. <3

-- 
steph
