### ISSUE TITLE
Reimplement 'proj' feature using the 'proj' crate instead of 'proj-sys'

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geo#211]
Blocked on https://github.com/georust/rust-proj/issues/7

See the previous discussion here: https://github.com/georust/rust-geo/pull/190

https://github.com/georust/rust-geo/blob/master/geo/src/algorithm/proj.rs

We couldn't implement it using `proj` because of a cyclic dependency issue. This will no longer be an issue once `rust-proj` switches to `geo-types`.

**Comment by urschrei** [comment]
I'll fix this if nobody else takes it, since I created the mess in the first place 😩
