### ISSUE TITLE
Use of algorithms traits in geo-types

### ISSUE THREAD

**Issue by urschrei** [georust/rust-geo#217]
I'm implementing some new methods on `Point`, and some of them require traits from `geo`, but I'm confused as to what to do now; looking at `geo-types/src/algorithms.rs`, it looks like we have to port over anything we want to use – but copy and pasting 250 loc of `contains.rs` seems like a bad idea…

**Comment by frewsxcv** [comment]
Can you share more information about the new method you're wanting to add and which algorithms it depends on? Just trying to understand your scenario a little more

**Comment by urschrei** [comment]
I may have been confusing myself – I was trying to add some methods to `Polygon` which depend on the functionality in `Contains`. For example, the (now slightly adapted, so it just takes a `Polygon` and `Point`): [ring_contains_point](https://github.com/urschrei/rust-geo/blob/new_polygon_distance/geo/src/algorithm/euclidean_distance.rs#L279-L291) function. Originally, I had impl'd it directly on `Polygon`, but that doesn't seem to be possible anymore because the crates are split.

**Comment by frewsxcv** [comment]
Ah, at least with the current design, you'd have to add a new algorithm to accomplish that. I also wouldn't be opposed to adding a new `Ring` type and implementing `Contains` for it.

**Comment by urschrei** [comment]
Yep, I think it's just a case of getting used to the new design, and working around some of its constraints for now. `Ring` is certainly something to think about, though…

**Comment by frewsxcv** [comment]
I'll open a PR today or tomorrow implementing `Ring`, I'll address https://github.com/georust/rust-geo/issues/166 in the process
