### ISSUE TITLE
Interactions between geo and geo-types

### ISSUE THREAD

**Issue by urschrei** [georust/rust-geo#221]
I'm running into a confusing problem when making modifications to a trait impl. I'm trying to alter the impl of `SpatialObject` on `Line<T>`, so that it also works for `&Line<T>`:

https://github.com/georust/rust-geo/blob/10b561bef20e80220b17d964fef487bacc63227f/geo-types/src/lib.rs#L433-L456

But changes to the impl aren't apparent within RLS, when running `cargo check`, or `cargo test`. Using `--all-features` with cargo also has no effect. Even removing the impl entirely has no effect. I've tried `cargo clean`, ensuring my editor's closed so nothing is cached, but I'm not sure what's going on. I'm just wondering whether anyone can repro this.

**Comment by frewsxcv** [comment]
Ah so you're running into this because of:

https://github.com/georust/rust-geo/blob/master/geo/Cargo.toml#L22

I think we should maybe change this to a relative path, like:

https://github.com/servo/webrender/blob/master/webrender/Cargo.toml#L42

**Comment by urschrei** [comment]
Yep, switching to the relative path fixes it.
