### ISSUE TITLE
Generic numeric type for all structs

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geo#25]
We should allow the user to use whatever numeric type they want (e.g. `f64`, `f32`, `i64`). Just need to parameterize it.

**Comment by zarch** [comment]
Do we really need to use "whatever numeric type" to define spatial coordinates?
To me it looks like f64 is the right type in this case... I don't see much value in supporting general numeric types.

**Comment by TeXitoi** [comment]
Using 32 bits integer is enough for precision and 2 times smaller. But it can be slower and less convenient.

**Comment by frewsxcv** [comment]
Considering both of you expected different types, I think this is the reason why it should be generic :)

**Comment by frewsxcv** [comment]
Completed in #30 by @Kerosene2000 and @zarch
