### ISSUE TITLE
Point/Line distance function defined twice

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geo#252]
On paper, these sound like they do the same thing, but it looks like the implementation might be different?

https://github.com/georust/rust-geo/blob/fbcabaae3dc5f2f0dfe73ec97ae2b22475d4ae82/geo/src/algorithm/euclidean_distance.rs#L74-L96

https://github.com/georust/rust-geo/blob/fbcabaae3dc5f2f0dfe73ec97ae2b22475d4ae82/geo/src/algorithm/simplify.rs#L5-L19

**Comment by urschrei** [comment]
Returns the same values, too. PR incoming…

**Comment by frewsxcv** [comment]
There's also this one too:

https://github.com/georust/rust-geo/blob/63f26b5c0692c60aecaac6c95746502bb91fa0df/geo/src/algorithm/convexhull.rs#L58-L71
