### ISSUE TITLE
Unnecessary slope contional check

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geo#253]
https://github.com/georust/rust-geo/blob/fbcabaae3dc5f2f0dfe73ec97ae2b22475d4ae82/geo/src/algorithm/polygon_distance_fast_path.rs#L494-L500

Shouldn't both branches of this conditional always result in the same thing?

i.e.: are these always the same?

```
(y₁ - y₀) / (x₁ - x₀)
```
```
(y₀ - y₁) / (x₀ - x₁)
```

Examples in iPython:

```python
In [1]: a = (4., 6.)

In [2]: b = (3., -20.)

In [3]: (b[1] - a[1]) / (b[0] - a[0])
Out[3]: 26.0

In [4]: (a[1] - b[1]) / (a[0] - b[0])
Out[4]: 26.0
```
```python
In [1]: a = (4., 6.)

In [2]: b = (8., -20.)

In [3]: (a[1] - b[1]) / (a[0] - b[0])
Out[3]: -6.5

In [4]: (b[1] - a[1]) / (b[0] - a[0])
Out[4]: -6.5
```

**Comment by urschrei** [comment]
Oh that never occurred to me. I've just checked the original, and I ported it correctly (ancient Java):

    else {
        vertical = false;
        if (p1.x > p1next.x)
            slope = (p1.y - p1next.y) / (p1.x - p1next.x);
        else
            slope = (p1next.y - p1.y) / (p1next.x - p1.x);
    }

So it seems to be an oversight in the original…
