### ISSUE TITLE
Spade 1.5.0 causes tests to fail

### ISSUE THREAD

**Issue by urschrei** [georust/rust-geo#263]
I can repro the failures, but I currently have no idea why they're occurring (I can't repro them using Spade's native types, which makes me wonder whether I've messed up a trait implementation somewhere.)

**Comment by urschrei** [comment]
Welp, doesn't look like it's the `SpatialObject` impl on `Line`…

**Comment by urschrei** [comment]
Issue open here: https://github.com/Stoeoef/spade/issues/32

**Comment by urschrei** [comment]
(We should just pin Spade 1.4.0 'til this is fixed)

**Comment by frewsxcv** [comment]
https://github.com/georust/rust-geo/pull/266
