### ISSUE TITLE
Publish Bbox struct in geo-types?

### ISSUE THREAD

**Issue by amatissart** [georust/rust-geo#292]
The `Bbox` struct is currently duplicated in both [geo-types](https://github.com/georust/rust-geo/blob/master/geo-types/src/algorithms.rs#L78) and [geo](https://github.com/georust/rust-geo/blob/master/geo/src/types.rs#L9).  
In my use case I would find useful to get `Bbox` published in geo-types, so that a standard serialization could be implemented in rust-geojson for example.  

What do you think?
Maybe it would help to refactor some of this code first ?

**Comment by frewsxcv** [comment]
This seems good to me. While we're shuffling things around, I also might be in favor of renaming it to just `Box`. Here are a couple other examples of other libraries:

- boost geometry calls it "box" https://www.boost.org/doc/libs/1_67_0/libs/geometry/doc/html/geometry/reference/models/model_box.html
- geos calls it "envelope" http://geos.osgeo.org/doxygen/classgeos_1_1geom_1_1Envelope.html
- shapely calls it "box" http://toblerity.org/shapely/shapely.geometry.html
- go.geo calls it "bound" https://godoc.org/github.com/paulmach/go.geo#Bound

**Comment by frewsxcv** [comment]
haha just kidding. `Box` is already a thing in Rust 🙃

**Comment by frewsxcv** [comment]
Opened a pull request for this: https://github.com/georust/rust-geo/pull/295
