### ISSUE TITLE
Change struct property names: Point {lat, lng} -> {x, y}

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geo#3]
https://github.com/georust/rust-geo/blob/38fe34109bb7dd2001c0ea9153b9c1dca98a44e8/src/point.rs

It's more concise and more aligned with existing specifications. Don't worry about Y and Z for now

**Comment by Turbo87** [comment]
maybe it actually makes more sense to use an array instead so that we don't have to worry about naming the components?

**Comment by frewsxcv** [comment]
@Turbo87 One potential issue I have with arrays is that I don't want users to put in more than 2 dimensions thinking it's going to work. If we're just looking to avoid naming the fields, we should change it to be a 'tuple struct': https://doc.rust-lang.org/nightly/reference.html#structs

**Comment by Turbo87** [comment]
@frewsxcv that's why I wrote array, not vector ;)

but I agree that a tuple struct looks much more suited here.
