### ISSUE TITLE
Implement spherical distance

### ISSUE THREAD

**Issue by tmcw** [georust/rust-geo#47]
https://github.com/georust/rust-geo/blob/master/src/algorithm/distance.rs

Currently it looks like rust-geo calculates distance with Euclidean distance, so it's in degrees. That can be useful, but is not typical for geo math: instead, Haversine distance or Vincenty distance is used - the latter is slightly more accurate but also somewhat slower.

Happy to contribute a patch if people agree with this direction.

**Comment by frewsxcv** [comment]
This is a great idea! I think it makes sense to group these under the same `Distance` trait. 

There are a few ways I can think to do this:

1. Separate methods

```
trait Distance {
    fn euclidean_distance(..)
    fn haversine_distance(..)
    fn haversine_distance(..)
}
```

2. Single method, enum param

```
enum DistanceAlgorithm {
    Euclidean,
    Haversine,
    Vincenty,
}

trait Distance {
    fn distance(algorithm: DistanceAlgorithm, ...)
}
```

3. Single method, parameterized algorithm. The [`Rand` trait does something similar such that it takes a `Rng` trait as input](https://doc.rust-lang.org/rand/rand/trait.Rand.html).

```
trait Distance {
    fn distance<A: DistanceAlgorithm>(..)
}

trait EuclideanAlgorithm {
   ..
}

struct Euclidean;

impl DistanceAlgorithm for Euclidean {
  ..
}
```

I just hastily wrote this up for the sake of giving you an answer faster. I haven't given it too much thought right now, but I'm leaning towards option 3.

**Comment by sfackler** [comment]
The rand-style approach is definitely what I would go with.

**Comment by sfackler** [comment]
Assuming `DistanceAlgorithm` has a static method, I'd go with `enum Euclidian {}` specifically since you never need to actually instantiate an instance of it, btw.

**Comment by frewsxcv** [comment]
Relevant conversation from IRC:

```
<frewsxcv> sfackler: what do you mean by `enum Euclidean {}`?
<sfackler> frewsxcv: since Euclidian will only be used in a trait bound, you never need to make an instance of it
<sfackler> frewsxcv: defining an enum with no variants is a common way of expressing a type that can't be instantiated
<frewsxcv> sfackler: Is that different than an empty struct?
<sfackler> frewsxcv: "struct Euclidian; let foo = Euclidian;" is valid
<sfackler> frewsxcv: "enum Euclidian {}; let foo = Euclidian" isn't
```

**Comment by zarch** [comment]
Just a doubt, are Haversine and Vincenty distance valid only for lat/lon coordinate systems?

**Comment by jdroenner** [comment]
Maybe we are at a point where we should think about coordinate systems in rust-geo  (#32)

**Comment by frewsxcv** [comment]
haversine was implemented in https://github.com/georust/rust-geo/pull/90

there's a new tracking issue for vincenty https://github.com/georust/rust-geo/issues/205
