### ISSUE TITLE
Perpendicular distance and LineString simplification

### ISSUE THREAD

**Issue by urschrei** [georust/rust-geo#54]
Is there any interest in a `simplify` method for LineStrings, using Douglas–Peucker? I've just finished implementing it in a separate crate, and then realised it might be useful here. This would also supply a perpendicular distance (from a LineString to a Point) method…

**Comment by frewsxcv** [comment]
I don't see why not, so +1 from me. I think a `Simplify` trait should be appropriate. Are there any other popular algorithms for doing simplify besides Douglas-Peucker?

**Comment by urschrei** [comment]
Hmm there's Visvalingam-Whyatt, too ([Mike Bostock](https://bost.ocks.org/mike/simplify/) has a nice demo of it).
From a quick look at the source, it looks a bit more complex than RDP to implement. I'd certainly be interested in working *with* someone on it, if people are interested.

**Comment by urschrei** [comment]
Sounds good to me!
