### ISSUE TITLE
How best to calculate Point to Polygon distance?

### ISSUE THREAD

**Issue by urschrei** [georust/rust-geo#59]
I'm working on an algorithm that requires calculating the minimum signed distance from a Point to a Polygon exterior (negative implies that the point lies inside the Polygon / `polygon.contains(point)` is `true`).
I can't see a good way to do this, currently – I've implemented point-line-distance in [simplify](https://github.com/georust/rust-geo/blob/master/src/algorithm/simplify.rs#L6-L18), but that's for segments, and there's currently no way to get Polygon exterior ring segments. Or is there? If anyone can think of an approach here, or point to an existing implementation I'd be very grateful (and I'll implement it ASAP)

**Comment by frewsxcv** [comment]
> currently – I've implemented point-line-distance in simplify

This is a tangential thought, but maybe we could move this point-line-distance implementation into   the `Distance` trait? e.g. `impl<T> Distance<T, LineString<T>> for Point<T> where T: Float`

> there's currently no way to get Polygon exterior ring segments

Can't you get the exterior ring segments from the first value in a `Polygon`? (see https://github.com/georust/rust-geo/issues/60). Or maybe I'm misreading something here.

**Comment by urschrei** [comment]
Hmm I think you're right. RE moving pld to `Distance`, I'll have a look at that this week.
