### ISSUE TITLE
`centroid` returns incorrect result when multiplogon consists of polygon in different clockwise

### ISSUE THREAD

**Issue by xlqian** [georust/rust-geo#92]
Consider: 
A Multi polygon consists of two polygon `[p(0., 0.), p(2., 0.), p(2., 2.), p(0., 2.), p(0., 0.)] ` (clockwise) and `[p(0., 0.), p(-2., 0.), p(-2., 2.), p(0., 2.), p(0., 0.)]`(anti-clockwise),  whose centroid is (0,1).

Current computation gives an incorrect result `(Nan, Nan)`.

**Comment by frewsxcv** [comment]
Fixed in #91
